/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "contract"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="contract", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ContractEntity.countAll", query="SELECT COUNT(x) FROM ContractEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class ContractEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="contract_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "contract_contract_id_pk_seq")
    @SequenceGenerator(name = "contract_contract_id_pk_seq", sequenceName = "contract_contract_id_pk_seq")
    protected Integer    contractId   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	// "employmentId" (column "employment_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonBackReference("EmploymentEntity_ContractEntity")
    @ManyToOne
    @JoinColumn(name="employment_id", referencedColumnName="employment_id")
    protected EmploymentEntity employment  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ContractEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setContractId( Integer contractId ) {
        this.contractId = contractId ;
    }
    public Integer getContractId() {
        return this.contractId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEmployment( EmploymentEntity employment ) {
        this.employment = employment;
    }
    public EmploymentEntity getEmployment() {
        return this.employment;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(contractId);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
