/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "employer_contact"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="employer_contact", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EmployerContactEntity.countAll", query="SELECT COUNT(x) FROM EmployerContactEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class EmployerContactEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="employer_contact_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "employer_contact_employer_contact_id_pk_seq")
    @SequenceGenerator(name = "employer_contact_employer_contact_id_pk_seq", sequenceName = "employer_contact_employer_contact_id_pk_seq")
    protected Integer    employerContactId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="contact_name", length=10)
    protected String     contactName  ;

    @Column(name="contact_type", length=10)
    protected String     contactType  ;

    @Column(name="contact_body", length=10)
    protected String     contactBody  ;

	// "employerId" (column "employer_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonBackReference("EmployerEntity_EmployerContactEntity")
    @ManyToOne
    @JoinColumn(name="employer_id", referencedColumnName="employer_id")
    protected EmployerEntity employer    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EmployerContactEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setEmployerContactId( Integer employerContactId ) {
        this.employerContactId = employerContactId ;
    }
    public Integer getEmployerContactId() {
        return this.employerContactId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : contact_name ( varchar ) 
    public void setContactName( String contactName ) {
        this.contactName = contactName;
    }
    public String getContactName() {
        return this.contactName;
    }

    //--- DATABASE MAPPING : contact_type ( varchar ) 
    public void setContactType( String contactType ) {
        this.contactType = contactType;
    }
    public String getContactType() {
        return this.contactType;
    }

    //--- DATABASE MAPPING : contact_body ( varchar ) 
    public void setContactBody( String contactBody ) {
        this.contactBody = contactBody;
    }
    public String getContactBody() {
        return this.contactBody;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEmployer( EmployerEntity employer ) {
        this.employer = employer;
    }
    public EmployerEntity getEmployer() {
        return this.employer;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(employerContactId);
        sb.append("]:"); 
        sb.append(contactName);
        sb.append("|");
        sb.append(contactType);
        sb.append("|");
        sb.append(contactBody);
        return sb.toString(); 
    } 

}
