/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "employer"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="employer", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EmployerEntity.countAll", query="SELECT COUNT(x) FROM EmployerEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class EmployerEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="employer_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "employer_employer_id_pk_seq")
    @SequenceGenerator(name = "employer_employer_id_pk_seq", sequenceName = "employer_employer_id_pk_seq")
    protected Integer    employerId   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=10)
    protected String     name         ;

    @Column(name="office_address", length=10)
    protected String     officeAddress ;

    @Column(name="office_postcode", length=10)
    protected String     officePostcode ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonManagedReference("EmployerEntity_EmployerContactEntity")
    @OneToMany(mappedBy="employer", targetEntity=EmployerContactEntity.class)
    protected List<EmployerContactEntity> listOfEmployerContact;

    @JsonManagedReference("EmployerEntity_EmploymentEntity")
    @OneToMany(mappedBy="employer", targetEntity=EmploymentEntity.class)
    protected List<EmploymentEntity> listOfEmployment;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EmployerEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setEmployerId( Integer employerId ) {
        this.employerId = employerId ;
    }
    public Integer getEmployerId() {
        return this.employerId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : office_address ( varchar ) 
    public void setOfficeAddress( String officeAddress ) {
        this.officeAddress = officeAddress;
    }
    public String getOfficeAddress() {
        return this.officeAddress;
    }

    //--- DATABASE MAPPING : office_postcode ( varchar ) 
    public void setOfficePostcode( String officePostcode ) {
        this.officePostcode = officePostcode;
    }
    public String getOfficePostcode() {
        return this.officePostcode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfEmployerContact( List<EmployerContactEntity> listOfEmployerContact ) {
        this.listOfEmployerContact = listOfEmployerContact;
    }
    public List<EmployerContactEntity> getListOfEmployerContact() {
        return this.listOfEmployerContact;
    }

    public void setListOfEmployment( List<EmploymentEntity> listOfEmployment ) {
        this.listOfEmployment = listOfEmployment;
    }
    public List<EmploymentEntity> getListOfEmployment() {
        return this.listOfEmployment;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(employerId);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(officeAddress);
        sb.append("|");
        sb.append(officePostcode);
        return sb.toString(); 
    } 

}
