/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "subscription_type"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="subscription_type", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SubscriptionTypeEntity.countAll", query="SELECT COUNT(x) FROM SubscriptionTypeEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class SubscriptionTypeEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="subscription_type_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "subscription_type_subscription_type_id_pk_seq")
    @SequenceGenerator(name = "subscription_type_subscription_type_id_pk_seq", sequenceName = "subscription_type_subscription_type_id_pk_seq")
    protected Integer    subscriptionTypeId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=30)
    protected String     name         ;

    @Column(name="rate", nullable=false)
    protected BigDecimal rate         ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonManagedReference("SubscriptionTypeEntity_SubscriptionEntity")
    @OneToMany(mappedBy="subscriptionType", targetEntity=SubscriptionEntity.class)
    protected List<SubscriptionEntity> listOfSubscription;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SubscriptionTypeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSubscriptionTypeId( Integer subscriptionTypeId ) {
        this.subscriptionTypeId = subscriptionTypeId ;
    }
    public Integer getSubscriptionTypeId() {
        return this.subscriptionTypeId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : rate ( numeric ) 
    public void setRate( BigDecimal rate ) {
        this.rate = rate;
    }
    public BigDecimal getRate() {
        return this.rate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfSubscription( List<SubscriptionEntity> listOfSubscription ) {
        this.listOfSubscription = listOfSubscription;
    }
    public List<SubscriptionEntity> getListOfSubscription() {
        return this.listOfSubscription;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(subscriptionTypeId);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(rate);
        return sb.toString(); 
    } 

}
