/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "subscription"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="subscription", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SubscriptionEntity.countAll", query="SELECT COUNT(x) FROM SubscriptionEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class SubscriptionEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="subscription_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "subscription_subscription_id_pk_seq")
    @SequenceGenerator(name = "subscription_subscription_id_pk_seq", sequenceName = "subscription_subscription_id_pk_seq")
    protected Integer    subscriptionId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="start_date_time", nullable=false)
    protected Date       startDateTime ;

    @Temporal(TemporalType.DATE)
    @Column(name="end_date_time")
    protected Date       endDateTime  ;

	// "prorataUserId" (column "prorata_user_id") is not defined by itself because used as FK in a link 
	// "subscriptionTypeId" (column "subscription_type_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonBackReference("ProrataUserEntity_SubscriptionEntity")
    @ManyToOne
    @JoinColumn(name="prorata_user_id", referencedColumnName="prorata_user_id")
    protected ProrataUserEntity prorataUser ;

    @JsonBackReference("SubscriptionTypeEntity_SubscriptionEntity")
    @ManyToOne
    @JoinColumn(name="subscription_type_id", referencedColumnName="subscription_type_id")
    protected SubscriptionTypeEntity subscriptionType;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SubscriptionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSubscriptionId( Integer subscriptionId ) {
        this.subscriptionId = subscriptionId ;
    }
    public Integer getSubscriptionId() {
        return this.subscriptionId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : start_date_time ( date ) 
    public void setStartDateTime( Date startDateTime ) {
        this.startDateTime = startDateTime;
    }
    public Date getStartDateTime() {
        return this.startDateTime;
    }

    //--- DATABASE MAPPING : end_date_time ( date ) 
    public void setEndDateTime( Date endDateTime ) {
        this.endDateTime = endDateTime;
    }
    public Date getEndDateTime() {
        return this.endDateTime;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setProrataUser( ProrataUserEntity prorataUser ) {
        this.prorataUser = prorataUser;
    }
    public ProrataUserEntity getProrataUser() {
        return this.prorataUser;
    }

    public void setSubscriptionType( SubscriptionTypeEntity subscriptionType ) {
        this.subscriptionType = subscriptionType;
    }
    public SubscriptionTypeEntity getSubscriptionType() {
        return this.subscriptionType;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(subscriptionId);
        sb.append("]:"); 
        sb.append(startDateTime);
        sb.append("|");
        sb.append(endDateTime);
        return sb.toString(); 
    } 

}
