/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "tax_bracket"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tax_bracket", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TaxBracketEntity.countAll", query="SELECT COUNT(x) FROM TaxBracketEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class TaxBracketEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="tax_bracket_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tax_bracket_tax_bracket_id_pk_seq")
    @SequenceGenerator(name = "tax_bracket_tax_bracket_id_pk_seq", sequenceName = "tax_bracket_tax_bracket_id_pk_seq")
    protected Integer    taxBracketId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="year")
    protected Date       year         ;

    @Column(name="personal_allowance")
    protected BigDecimal personalAllowance ;

    @Column(name="percent_deduction")
    protected BigDecimal percentDeduction ;

    @Column(name="tax_code", length=10)
    protected String     taxCode      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonManagedReference("TaxBracketEntity_TaxDeductionEntity")
    @OneToMany(mappedBy="taxBracket", targetEntity=TaxDeductionEntity.class)
    protected List<TaxDeductionEntity> listOfTaxDeduction;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TaxBracketEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTaxBracketId( Integer taxBracketId ) {
        this.taxBracketId = taxBracketId ;
    }
    public Integer getTaxBracketId() {
        return this.taxBracketId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : year ( date ) 
    public void setYear( Date year ) {
        this.year = year;
    }
    public Date getYear() {
        return this.year;
    }

    //--- DATABASE MAPPING : personal_allowance ( numeric ) 
    public void setPersonalAllowance( BigDecimal personalAllowance ) {
        this.personalAllowance = personalAllowance;
    }
    public BigDecimal getPersonalAllowance() {
        return this.personalAllowance;
    }

    //--- DATABASE MAPPING : percent_deduction ( numeric ) 
    public void setPercentDeduction( BigDecimal percentDeduction ) {
        this.percentDeduction = percentDeduction;
    }
    public BigDecimal getPercentDeduction() {
        return this.percentDeduction;
    }

    //--- DATABASE MAPPING : tax_code ( varchar ) 
    public void setTaxCode( String taxCode ) {
        this.taxCode = taxCode;
    }
    public String getTaxCode() {
        return this.taxCode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTaxDeduction( List<TaxDeductionEntity> listOfTaxDeduction ) {
        this.listOfTaxDeduction = listOfTaxDeduction;
    }
    public List<TaxDeductionEntity> getListOfTaxDeduction() {
        return this.listOfTaxDeduction;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(taxBracketId);
        sb.append("]:"); 
        sb.append(year);
        sb.append("|");
        sb.append(personalAllowance);
        sb.append("|");
        sb.append(percentDeduction);
        sb.append("|");
        sb.append(taxCode);
        return sb.toString(); 
    } 

}
