/*
 * Created on 5 Mar 2016 ( Time 20:49:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.pawsey.prorata.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.*;

/**
 * Persistent class for entity stored in table "tax_deduction"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tax_deduction", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TaxDeductionEntity.countAll", query="SELECT COUNT(x) FROM TaxDeductionEntity x" )
} )
@JsonIgnoreProperties(ignoreUnknown = true) 
public class TaxDeductionEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="tax_deduction_id", nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tax_deduction_tax_deduction_id_pk_seq")
    @SequenceGenerator(name = "tax_deduction_tax_deduction_id_pk_seq", sequenceName = "tax_deduction_tax_deduction_id_pk_seq")
    protected Integer    taxDeductionId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="amount")
    protected BigDecimal amount       ;

	// "taxBracketId" (column "tax_bracket_id") is not defined by itself because used as FK in a link 
	// "paymentId" (column "payment_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonBackReference("PaymentEntity_TaxDeductionEntity")
    @ManyToOne
    @JoinColumn(name="payment_id", referencedColumnName="payment_id")
    protected PaymentEntity payment     ;

    @JsonBackReference("TaxBracketEntity_TaxDeductionEntity")
    @ManyToOne
    @JoinColumn(name="tax_bracket_id", referencedColumnName="tax_bracket_id")
    protected TaxBracketEntity taxBracket  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TaxDeductionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTaxDeductionId( Integer taxDeductionId ) {
        this.taxDeductionId = taxDeductionId ;
    }
    public Integer getTaxDeductionId() {
        return this.taxDeductionId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : amount ( numeric ) 
    public void setAmount( BigDecimal amount ) {
        this.amount = amount;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPayment( PaymentEntity payment ) {
        this.payment = payment;
    }
    public PaymentEntity getPayment() {
        return this.payment;
    }

    public void setTaxBracket( TaxBracketEntity taxBracket ) {
        this.taxBracket = taxBracket;
    }
    public TaxBracketEntity getTaxBracket() {
        return this.taxBracket;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(taxDeductionId);
        sb.append("]:"); 
        sb.append(amount);
        return sb.toString(); 
    } 

}
